name: rawphoto
favicon: null
layout_spectrum: 0.25677
typography_spectrum: 0.20335
title: rawphoto - Nelson Cristo Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a417f'
    - '#100d1d'
    - '#527cbe'
    - '#9fafc6'
    - '#ededed'
  brandStrength: 0.414524256484583
  lightness: 0.6260869002435356
  saturation: 0.375
  rhythmicContrast: 0.9377013412304223
purpose: []
