layout_spectrum: 0.5098725478372325
typography_spectrum: 0.13732668662572853
color:
  saturation: 0.6152536465181498
  brandStrength: 0.043073567540689126
  rhythmicContrast: 0.039450462685971716
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  lightness: 0.9742879110856885
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-44801613-2
  facebook: null
author:
  name: Copyright © 2017 Nelson Cristo Photography - All Rights Reserved
  email: nelson.cristo@gmail.com
  url: www.rawphoto.pt
logo: null
name: rawphoto
url: 'http://rawphoto.pt'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: nothingmatters
    id: 4f0e7e36-4917-469e-a2a6-5759badaed23
    type: content
  - name: moods...
    id: a08bb706-823e-40f5-b5e9-9adebdc61fb2
    type: content
  - name: about
    id: 27f069db-2abe-4395-8e1b-b9dec6db0f57
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Nelson Cristo Photography
content: []
description: >-
  Mineral Resources & related manmade "industrial landscape
  architecture"/Travel/Social Photography and... experiments. Sharing to, and
  from others. Enjoy!
purpose:
  - type: contact
    url: 'mailto:nelson.cristo@gmail.com'
    label: Contact
github: true
