name: rawphoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51334
title: Nelson Cristo Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.414524256484583
  lightness: 0.6260869002435356
  saturation: 0.5370708468835801
  rhythmicContrast: 0.9377013412304223
purpose: []
