layout_spectrum: 0.24270393051640451
typography_spectrum: 0.7821156156689187
color:
  saturation: 0.8665913395449003
  brandStrength: 0.07135245286896456
  rhythmicContrast: 0.6942268466688508
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.21389255612793534
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: '@ncristo'
  google: UA-44801613-2
  facebook: null
author:
  name: Copyright © 2017 Nelson Cristo Photography - All Rights Reserved
  email: nelson.cristo@gmail.com
  url: www.rawphoto.pt
logo: null
name: rawphoto
url: 'http://rawphoto.pt'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: nothingmatters
    id: 4f0e7e36-4917-469e-a2a6-5759badaed23
    type: content
  - name: moods...
    id: a08bb706-823e-40f5-b5e9-9adebdc61fb2
    type: content
  - name: about
    id: 27f069db-2abe-4395-8e1b-b9dec6db0f57
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Nelson Cristo Photography
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ef186d70-1535-463f-8187-f36c87ce1ee0.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ef186d70-1535-463f-8187-f36c87ce1ee0.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Mineral Resources & related manmade "industrial landscape
  architecture"/Travel/Social Photography and... experiments. Sharing to, and
  from others. Enjoy!
purpose:
  - type: contact
    url: 'mailto:nelson.cristo@gmail.com'
    label: Contact
  - type: external
    url: 'http://rawphoto.pt/rss.xml'
    label: 'Subscribe RRS Feedhttp://rawphoto.pt/rss.xml'
github: true
